services:
  pyspark_project_notebook:
    hostname: pyspark
    container_name: pyspark_project_notebook
    build: 
       context: .
       dockerfile: Dockerfile
    image: pyspark_custom_pacmann
    restart: on-failure
    environment:
      JUPYTER_ENABLE_LAB: "yes"
    ports:
      - ${SPARK_NOTEBOOK_PORT}:8888
      - ${SPARK_JOB_PORT}:4040
    volumes:
      - ./script:/home/jovyan/work
    networks:
      - pyspark_project_net

  pyspark_project_minio:
    image: minio/minio:latest
    hostname: minio
    container_name: pyspark_project_minio
    ports:
      - "9000:9000"
      - "9001:9001"
    volumes:
      - ./minio/data/:/data/
    environment:
      - MINIO_ROOT_USER=${MINIO_ROOT_USER}
      - MINIO_ROOT_PASSWORD=${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9001"
    networks:
      - pyspark_project_net

  pyspark_project_source_db:
    image: postgres:latest
    hostname: source_db
    container_name: pyspark_project_source_db
    restart: on-failure
    environment:
      - POSTGRES_DB=${SOURCE_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./database/source_data/init_source.sql:/docker-entrypoint-initdb.d/init_source.sql
    ports:
      - ${SOURCE_DB_PORT}:5432 
    networks:
      - pyspark_project_net

  pyspark_project_staging_db:
    image: postgres:latest
    hostname: staging_db
    container_name: pyspark_project_staging_db
    restart: on-failure
    environment:
      - POSTGRES_DB=${STG_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./database/staging_data/init_stg.sql:/docker-entrypoint-initdb.d/init_stg.sql
    ports:
      - ${STG_DB_PORT}:5432 
    networks:
      - pyspark_project_net

  pyspark_project_dwh_db:
    image: postgres:latest
    hostname: dwh_db
    container_name: pyspark_project_dwh_db
    restart: on-failure
    environment:
      - POSTGRES_DB=${DWH_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./database/dwh_data/init_dwh.sql:/docker-entrypoint-initdb.d/init_dwh.sql
    ports:
      - ${DWH_DB_PORT}:5432 
    networks:
      - pyspark_project_net

  pyspark_project_log_db:
    image: postgres:latest
    hostname: log_db
    container_name: pyspark_project_log_db
    restart: on-failure
    environment:
      - POSTGRES_DB=${LOG_DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASS}
    volumes:
      - ./database/log_data/etl_log.sql:/docker-entrypoint-initdb.d/etl_log.sql
    ports:
      - ${LOG_DB_PORT}:5432 
    networks:
      - pyspark_project_net
  
networks:
  pyspark_project_net:
    driver: bridge